version: "3.8"

services:
  app:
    build: .
    container_name: ms-consumer
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}